In [1]:
import pandas as pd

data_dir = '/Users/davidebonaglia/Dropbox/Projects UNU/Excellent Science/'
H2020BiblioData = data_dir + 'H2020BiblioData&Indicators_ExcelScie_ResEuro_ProjIDs_v1.3.1.xlsx'

H2020BiblioData = pd.read_excel(H2020BiblioData)
H2020BiblioData.head(5)

,Digital Object Identifier (DOI),Funding Agency and Grant Number,Funding Award Numbers,Funding Organization,Funding Organization (w/ awd. num.),Funding Text,Open Access Indicator,ORCID Identifier (Open Researcher and Contributor ID)::ID,Author Address (Organization Only),Countries/Regions (Cleaned),...,programme_PROJ_ID_10,start_date_PROJ_ID_10,end_date_PROJ_ID_10,programmes_PROJ_ID_10,mv_CD_ACTION_TYPE_PROJ_ID_10,mv_CD_DG_PROJ_ID_10,mv_CD_THEMA_PROJ_ID_10,mv_CD_TOPIC_PROJ_ID_10,CD_PROJECT_CNT,CD_PROJECT_FRAC
0,10.1001/jama.2016.0312,0,0,0,0,0,0,0000-0003-0747-4471,Hartford Hosp|Radboud Univ Nijmegen,Netherlands|USA,...,0,1899-12-30,1899-12-30,0,0,0,0,0,1,1.0
1,10.1001/jama.2016.1975,EUNICE KENNEDY SHRIVER NATIONAL INSTITUTE OF C...,098395|102215|104150|104150/Z/14/Z|323195|G050...,CIHRCanadian Institutes of Health Research (CI...,CIHRCanadian Institutes of Health Research (CI...,0,"Green Submitted, Green Accepted, Green Publish...",0000-0001-5079-2374|0000-0001-5620-473X|0000-0...,Bispebjerg & Frederiksberg Univ Hosp|Charite|C...,Australia|Canada|China|Denmark|Finland|Germany...,...,0,1899-12-30,1899-12-30,0,0,0,0,0,2,0.5
2,10.1001/jama.2016.20644,European Union's Innovative Medicines Initiati...,115854,European Federation of Pharmaceutical Industri...,European Federation of Pharmaceutical Industri...,This trial was funded by grant 115854 from the...,"Green Submitted, Bronze",0000-0001-6324-6559|0000-0002-6501-5524|0000-0...,Janssen|Univ Oxford,Netherlands|UK,...,0,1899-12-30,1899-12-30,0,0,0,0,0,1,1.0
3,10.1001/jama.2016.4218,European Union's Innovative Medicines Initiati...,115854,Crucell Holland|European Federation of Pharmac...,Crucell Holland|European Federation of Pharmac...,This trial was funded by the European Union's ...,Bronze,0000-0001-6324-6559|0000-0001-9827-9836|0000-0...,Bavarian Nord|Fred Hutchinson Canc Res Ctr|Oxf...,Germany|Netherlands|UK|USA,...,0,1899-12-30,1899-12-30,0,0,0,0,0,1,1.0
4,10.1001/jama.2017.6895,European Union/European Federation of Pharmace...,115372|115736|116020,European Union/European Federation of Pharmace...,European Union/European Federation of Pharmace...,This work has received grant support from the ...,0,0000-0001-8008-9727|0000-0002-2612-1797,Maastricht Univ|Vrije Univ Amsterdam Med Ctr,Netherlands,...,0,1899-12-30,1899-12-30,0,0,0,0,0,1,1.0

In [2]:
#xx = list(H2020BiblioData.columns.values)

In [3]:
#cd_project_01
cd_project_01 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_01', 'programme_PROJ_ID_01', '_mv_CD_ACTION_TYPE_PROJ_ID_01',
                                         'start_date_PROJ_ID_01', 'end_date_PROJ_ID_01', 'CD_PROJECT_FRAC']]

cd_project_01 = cd_project_01.drop_duplicates()

#rename columns
cd_project_01 = cd_project_01.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_01' : 'project_id',
                                                'programme_PROJ_ID_01': 'progr_proj_id',
                                                '_mv_CD_ACTION_TYPE_PROJ_ID_01': 'action_type_proj_id',
                                                'start_date_PROJ_ID_01' : 'starting_date',
                                                'end_date_PROJ_ID_01' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})
                                                

cd_project_01

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
0,10.1001/jama.2016.0312,655502,['H2020-MSCA'],MSCA-IF-EF-ST,2015-06-01,2017-12-01,1.0
1,10.1001/jama.2016.1975,633595,['H2020-SC1'],RIA,2015-04-01,2019-03-31,0.5
2,10.1001/jama.2016.20644,115854,['H2020-SC1'],JTI-IMI2-RIA,2014-12-01,2021-11-30,1.0
3,10.1001/jama.2016.4218,115854,['H2020-SC1'],JTI-IMI2-RIA,2014-12-01,2021-11-30,1.0
4,10.1001/jama.2017.6895,116020,['H2020-SC1'],RIA,2016-11-01,2018-10-31,1.0
...,...,...,...,...,...,...,...
123112,10.7900/jot.2017jan19.2147,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0
123113,10.7900/jot.20181apr19.2188,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0
123114,10.7900/jot.2018jun13.2222,691246,['H2020-MSCA'],MSCA-RISE,2016-01-01,2019-12-31,1.0
123115,10.7900/jot.2018mar08.2219,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0
123116,10.7900/jot.2020feb06.2268,844451,['H2020-MSCA'],MSCA-IF-EF-ST,2019-06-01,2021-05-31,1.0

In [4]:
#cd_project_02
cd_project_02 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_02', 'programme_PROJ_ID_02', 'mv_CD_ACTION_TYPE_PROJ_ID_02',
                                         'start_date_PROJ_ID_02', 'end_date_PROJ_ID_02', 'CD_PROJECT_FRAC']]

cd_project_02 = cd_project_02.drop_duplicates()
cd_project_02 = cd_project_02.loc[cd_project_02.CD_PROJECT_ID_02 != 0 ]

#rename columns
cd_project_02 = cd_project_02.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_02' : 'project_id',
                                                'programme_PROJ_ID_02': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_02': 'action_type_proj_id',
                                                'start_date_PROJ_ID_02' : 'starting_date',
                                                'end_date_PROJ_ID_02' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_02

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
1,10.1001/jama.2016.1975,669545,['H2020-ERC'],ERC-ADG,2015-11-01,2021-07-31,0.500000
6,10.1001/jama.2019.3820,669545,['H2020-ERC'],ERC-ADG,2015-11-01,2021-07-31,0.333333
8,10.1001/jama.2020.13719,833247,['H2020-ERC'],ERC-ADG,2019-10-01,2024-09-30,0.500000
16,10.1001/jamanetworkopen.2018.0725,758813,['H2020-ERC'],ERC-STG,2017-12-01,2022-11-30,0.500000
23,10.1001/jamanetworkopen.2019.1868,777394,['H2020-SC1'],JTI-IMI2-RIA,2018-06-01,2023-05-31,0.500000
...,...,...,...,...,...,...,...
123000,10.7566/JPSJ.87.041016,694097,['H2020-ERC'],ERC-ADG,2016-10-01,2021-09-30,0.500000
123024,10.7717/peerj.2946,691154,['H2020-MSCA'],MSCA-RISE,2016-07-01,2021-12-31,0.500000
123048,10.7717/peerj.5025,748167,['H2020-MSCA'],MSCA-IF-EF-ST,2017-10-02,2019-10-01,0.500000
123068,10.7717/peerj.7208,773921,['H2020-SC2'],RIA,2018-06-01,2023-05-31,0.500000
123088,10.7717/peerj.8984,774234,['H2020-SC2'],RIA,2018-05-01,2022-04-30,0.500000

In [5]:
#cd_project_03
cd_project_03 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_03', 'programme_PROJ_ID_03', 'mv_CD_ACTION_TYPE_PROJ_ID_03',
                                         'start_date_PROJ_ID_03', 'end_date_PROJ_ID_03', 'CD_PROJECT_FRAC']]

cd_project_03 = cd_project_03.drop_duplicates()
cd_project_03 = cd_project_03.loc[cd_project_03.CD_PROJECT_ID_03 != 0 ]

#rename columns
cd_project_03 = cd_project_03.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_03' : 'project_id',
                                                'programme_PROJ_ID_03': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_03': 'action_type_proj_id',
                                                'start_date_PROJ_ID_03' : 'starting_date',
                                                'end_date_PROJ_ID_03' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_03

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
6,10.1001/jama.2019.3820,733206,['H2020-SC1'],RIA,2017-01-01,2022-06-30,0.333333
602,10.1002/adfm.201908994,787410,['H2020-ERC'],ERC-ADG,2019-01-01,2023-12-31,0.333333
617,10.1002/adfm.201910259,777714,['H2020-MSCA'],MSCA-RISE,2018-01-01,2023-06-30,0.333333
619,10.1002/adfm.201910335,787510,['H2020-ERC'],ERC-ADG,2018-10-01,2023-09-30,0.250000
677,10.1002/adfm.202008032,819417,['H2020-ERC'],ERC-COG,2019-10-01,2024-09-30,0.333333
...,...,...,...,...,...,...,...
122498,10.7150/thno.34429,777682,['H2020-MSCA'],MSCA-RISE,2018-03-01,2022-02-28,0.333333
122514,10.7150/thno.47406,825159,['H2020-ERC'],ERC-POC,2018-12-01,2020-07-31,0.333333
122796,10.7554/eLife.49562,759432,['H2020-ERC'],ERC-STG,2018-01-01,2022-12-31,0.333333
122947,10.7554/eLife.60416,671208,['H2020-ERC'],ERC-ADG,2015-12-01,2021-05-31,0.333333
122962,10.7554/eLife.61710,847422,['H2020-SC1'],RIA,2020-01-01,2023-12-31,0.333333

In [6]:
#cd_project_04
cd_project_04 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_04', 'programme_PROJ_ID_04', 'mv_CD_ACTION_TYPE_PROJ_ID_04',
                                         'start_date_PROJ_ID_04', 'end_date_PROJ_ID_04', 'CD_PROJECT_FRAC']]

cd_project_04 = cd_project_04.drop_duplicates()
cd_project_04 = cd_project_04.loc[cd_project_04.CD_PROJECT_ID_04 != 0 ]

#rename columns
cd_project_04 = cd_project_04.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_04' : 'project_id',
                                                'programme_PROJ_ID_04': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_04': 'action_type_proj_id',
                                                'start_date_PROJ_ID_04' : 'starting_date',
                                                'end_date_PROJ_ID_04' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_04

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
619,10.1002/adfm.201910335,819242,['H2020-ERC'],ERC-COG,2019-11-01,2024-10-31,0.25
1728,10.1002/anie.201607084,661799,['H2020-MSCA'],MSCA-IF-EF-ST,2016-01-01,2018-01-18,0.25
10428,10.1007/s00204-018-2354-1,777365,['H2020-SC1'],JTI-IMI2-RIA,2017-09-01,2022-08-31,0.25
12453,10.1007/s10654-019-00502-9,757919,['H2020-ERC'],ERC-STG,2017-12-01,2023-11-30,0.25
12586,10.1007/s10686-018-9598-x,740963,['H2020-ERC'],ERC-ADG,2017-10-01,2022-09-30,0.20
...,...,...,...,...,...,...,...
120022,10.3847/2041-8213/aa91c9,725161,['H2020-ERC'],ERC-COG,2017-09-01,2022-07-31,0.20
120090,10.3847/2041-8213/aaf16a,726384,['H2020-ERC'],ERC-COG,2017-07-01,2022-12-31,0.25
121460,10.5194/bg-17-3439-2020,821003,['H2020-SC5'],RIA,2019-06-01,2023-05-31,0.25
121582,10.5194/essd-11-1783-2019,776810,['H2020-SC5'],RIA,2018-02-01,2022-01-31,0.20
121600,10.5194/essd-12-3269-2020,821003,['H2020-SC5'],RIA,2019-06-01,2023-05-31,0.25

In [7]:
#cd_project_05
cd_project_05 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_05', 'programme_PROJ_ID_05', 'mv_CD_ACTION_TYPE_PROJ_ID_05',
                                         'start_date_PROJ_ID_05', 'end_date_PROJ_ID_05', 'CD_PROJECT_FRAC']]

cd_project_05 = cd_project_05.drop_duplicates()
cd_project_05 = cd_project_05.loc[cd_project_05.CD_PROJECT_ID_05 != 0 ]

#rename columns
cd_project_05 = cd_project_05.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_05' : 'project_id',
                                                'programme_PROJ_ID_05': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_05': 'action_type_proj_id',
                                                'start_date_PROJ_ID_05' : 'starting_date',
                                                'end_date_PROJ_ID_05' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_05

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
12586,10.1007/s10686-018-9598-x,758892,['H2020-ERC'],ERC-STG,2018-01-01,2023-06-30,0.200000
17240,10.1016/j.biomaterials.2020.120580,861190,['H2020-MSCA'],MSCA-ITN-ETN,2019-10-01,2024-03-31,0.166667
18757,10.1016/j.cels.2018.06.002,757850,['H2020-ERC'],ERC-STG,2018-02-01,2023-01-31,0.200000
41367,10.1021/acs.jpclett.9b03574,823717,['H2020-INFRA'],RIA,2019-01-01,2023-06-30,0.200000
42177,10.1021/acs.nanolett.9b03837,793159,['H2020-MSCA'],MSCA-IF-EF-ST,2019-01-01,2020-12-31,0.200000
43796,10.1021/acsnano.9b06848,823717,['H2020-INFRA'],RIA,2019-01-01,2023-06-30,0.200000
47320,10.1038/s41417-020-00224-1,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.200000
48095,10.1038/s41467-018-08063-3,804110,['H2020-ERC'],ERC-STG,2018-11-01,2023-10-31,0.200000
51597,10.1038/s41597-020-00637-5,824143,['H2020-INFRA'],RIA,2018-12-01,2022-05-31,0.200000
53715,10.1038/s42005-019-0150-8,793159,['H2020-MSCA'],MSCA-IF-EF-ST,2019-01-01,2020-12-31,0.200000
58332,10.1051/0004-6361/201834878,797794,['H2020-MSCA'],MSCA-IF-EF-ST,2018-04-02,2020-04-01,0.200000
74548,10.1093/nar/gkaa1028,848158,['H2020-SC1'],RIA,2020-01-01,2023-12-31,0.200000
95940,10.1140/epjst/e2019-900087-0,764879,['H2020-MSCA'],MSCA-ITN-ETN,2017-10-01,2021-09-30,0.200000
102297,10.1186/s13073-020-0713-z,779257,['H2020-SC1'],RIA,2018-01-01,2022-12-31,0.142857
102298,10.1186/s13073-020-0716-9,824989,['H2020-SC1'],RIA,2019-01-01,2023-12-31,0.200000
105229,10.1371/journal.pgen.1006812,692145,['H2020-SEWP'],CSA,2016-01-01,2019-02-28,0.200000
109698,10.3389/fchem.2020.00496,852985,['H2020-SEWP'],CSA,2019-10-01,2022-09-30,0.111111
113103,10.3390/cancers12123744,895151,['H2020-MSCA'],MSCA-IF-EF-SE,2020-09-01,2022-08-31,0.200000
114733,10.3390/ijms21072313,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.200000
116010,10.3390/molecules25051181,857894,['H2020-MSCA'],MSCA-ITN-ETN,2019-11-01,2023-10-31,0.111111
116026,10.3390/molecules25092219,852985,['H2020-SEWP'],CSA,2019-10-01,2022-09-30,0.111111
116096,10.3390/molecules26113272,859908,['H2020-MSCA'],MSCA-ITN-ETN,2020-02-01,2024-01-31,0.100000
116533,10.3390/pharmaceutics12111022,872391,['H2020-MSCA'],MSCA-RISE,2020-05-01,2024-04-30,0.166667
116534,10.3390/pharmaceutics12111054,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.200000
116729,10.3390/polym13060907,859908,['H2020-MSCA'],MSCA-ITN-ETN,2020-02-01,2024-01-31,0.142857
120022,10.3847/2041-8213/aa91c9,730562,['H2020-INFRA'],RIA,2017-01-01,2020-12-31,0.200000
121582,10.5194/essd-11-1783-2019,821003,['H2020-SC5'],RIA,2019-06-01,2023-05-31,0.200000

In [8]:
#cd_project_06
cd_project_06 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_06', 'programme_PROJ_ID_06', 'mv_CD_ACTION_TYPE_PROJ_ID_06',
                                         'start_date_PROJ_ID_06', 'end_date_PROJ_ID_06', 'CD_PROJECT_FRAC']]

cd_project_06 = cd_project_06.drop_duplicates()
cd_project_06 = cd_project_06.loc[cd_project_06.CD_PROJECT_ID_06 != 0 ]

#rename columns
cd_project_06 = cd_project_06.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_06' : 'project_id',
                                                'programme_PROJ_ID_06': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_06': 'action_type_proj_id',
                                                'start_date_PROJ_ID_06' : 'starting_date',
                                                'end_date_PROJ_ID_06' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_06

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
17240,10.1016/j.biomaterials.2020.120580,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.166667
102297,10.1186/s13073-020-0713-z,785907,['H2020-FET'],SGA-RIA,2018-04-01,2020-03-31,0.142857
109698,10.3389/fchem.2020.00496,859908,['H2020-MSCA'],MSCA-ITN-ETN,2020-02-01,2024-01-31,0.111111
116010,10.3390/molecules25051181,859908,['H2020-MSCA'],MSCA-ITN-ETN,2020-02-01,2024-01-31,0.111111
116026,10.3390/molecules25092219,859908,['H2020-MSCA'],MSCA-ITN-ETN,2020-02-01,2024-01-31,0.111111
116096,10.3390/molecules26113272,860173,['H2020-MSCA'],MSCA-ITN-EID,2020-03-01,2024-04-30,0.100000
116533,10.3390/pharmaceutics12111022,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.166667
116729,10.3390/polym13060907,861190,['H2020-MSCA'],MSCA-ITN-ETN,2019-10-01,2024-03-31,0.142857

In [9]:
#cd_project_07
cd_project_07 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_07', 'programme_PROJ_ID_07', 'mv_CD_ACTION_TYPE_PROJ_ID_07',
                                         'start_date_PROJ_ID_07', 'end_date_PROJ_ID_07', 'CD_PROJECT_FRAC']]

cd_project_07 = cd_project_07.drop_duplicates()
cd_project_07 = cd_project_07.loc[cd_project_07.CD_PROJECT_ID_07 != 0 ]

#rename columns
cd_project_07 = cd_project_07.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_07' : 'project_id',
                                                'programme_PROJ_ID_07': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_07': 'action_type_proj_id',
                                                'start_date_PROJ_ID_07' : 'starting_date',
                                                'end_date_PROJ_ID_07' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_07

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
102297,10.1186/s13073-020-0713-z,825812,['H2020-SC1'],CSA,2018-11-01,2023-04-30,0.142857
109698,10.3389/fchem.2020.00496,860173,['H2020-MSCA'],MSCA-ITN-EID,2020-03-01,2024-04-30,0.111111
116010,10.3390/molecules25051181,860173,['H2020-MSCA'],MSCA-ITN-EID,2020-03-01,2024-04-30,0.111111
116026,10.3390/molecules25092219,860173,['H2020-MSCA'],MSCA-ITN-EID,2020-03-01,2024-04-30,0.111111
116096,10.3390/molecules26113272,861190,['H2020-MSCA'],MSCA-ITN-ETN,2019-10-01,2024-03-31,0.100000
116729,10.3390/polym13060907,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.142857

In [10]:
import numpy as np

#cd_project_08
#start_date_PROJ_ID_08 and end_date_PROJ_ID_08 are wrong. I added NaN values instead
cd_project_08 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_08', 'programme_PROJ_ID_08', 'mv_CD_ACTION_TYPE_PROJ_ID_08',
                                    'CD_PROJECT_FRAC']]

cd_project_08 = cd_project_08.drop_duplicates()
cd_project_08 = cd_project_08.loc[cd_project_08.CD_PROJECT_ID_08 != 0 ]

#rename columns
cd_project_08 = cd_project_08.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_08' : 'project_id',
                                                'programme_PROJ_ID_08': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_08': 'action_type_proj_id',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_08['starting_date'] = np.nan
cd_project_08['ending_date'] = np.nan

#rearrange columns 
cd_project_08 = cd_project_08[['publication', 'project_id', 'progr_proj_id', 'action_type_proj_id',
                                'starting_date', 'ending_date', 'fractional_counting']]

cd_project_08

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
109698,10.3389/fchem.2020.00496,861190,['H2020-MSCA'],MSCA-ITN-ETN,NaN,NaN,0.111111
116010,10.3390/molecules25051181,861190,['H2020-MSCA'],MSCA-ITN-ETN,NaN,NaN,0.111111
116026,10.3390/molecules25092219,861190,['H2020-MSCA'],MSCA-ITN-ETN,NaN,NaN,0.111111
116096,10.3390/molecules26113272,872391,['H2020-MSCA'],MSCA-RISE,NaN,NaN,0.100000

In [11]:
#cd_project_09
cd_project_09 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_09', 'programme_PROJ_ID_09', 'mv_CD_ACTION_TYPE_PROJ_ID_09',
                                         'start_date_PROJ_ID_09', 'end_date_PROJ_ID_09', 'CD_PROJECT_FRAC']]

cd_project_09 = cd_project_09.drop_duplicates()
cd_project_09 = cd_project_09.loc[cd_project_09.CD_PROJECT_ID_09 != 0 ]

#rename columns
cd_project_09 = cd_project_09.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_09' : 'project_id',
                                                'programme_PROJ_ID_09': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_09': 'action_type_proj_id',
                                                'start_date_PROJ_ID_09' : 'starting_date',
                                                'end_date_PROJ_ID_09' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_09

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
109698,10.3389/fchem.2020.00496,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.111111
116010,10.3390/molecules25051181,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.111111
116026,10.3390/molecules25092219,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.111111
116096,10.3390/molecules26113272,872860,['H2020-MSCA'],MSCA-RISE,2020-04-01,2025-03-31,0.100000

In [12]:
#cd_project_10
cd_project_10 = H2020BiblioData[[' Digital Object Identifier (DOI)', 'CD_PROJECT_ID_10', 'programme_PROJ_ID_10', 'mv_CD_ACTION_TYPE_PROJ_ID_10',
                                         'start_date_PROJ_ID_10', 'end_date_PROJ_ID_10', 'CD_PROJECT_FRAC']]

cd_project_10 = cd_project_10.drop_duplicates()
cd_project_10 = cd_project_10.loc[cd_project_10.CD_PROJECT_ID_10 != 0 ]

#rename columns
cd_project_10 = cd_project_10.rename(columns={' Digital Object Identifier (DOI)': 'publication',
                                                'CD_PROJECT_ID_10' : 'project_id',
                                                'programme_PROJ_ID_10': 'progr_proj_id',
                                                'mv_CD_ACTION_TYPE_PROJ_ID_10': 'action_type_proj_id',
                                                'start_date_PROJ_ID_10' : 'starting_date',
                                                'end_date_PROJ_ID_10' : 'ending_date',
                                                'CD_PROJECT_FRAC' : 'fractional_counting'})

cd_project_10

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
116096,10.3390/molecules26113272,952520,['H2020-SEWP'],CSA,2020-09-01,2023-08-31,0.1

In [13]:
#final database
data = cd_project_01.append(cd_project_02)
data = data.append(cd_project_03)
data = data.append(cd_project_04)
data = data.append(cd_project_05)
data = data.append(cd_project_06)
data = data.append(cd_project_07)
data = data.append(cd_project_08)
data = data.append(cd_project_09)
data = data.append(cd_project_10)

data = data.sort_values(by=['publication'], ascending = True)

data['starting_date'] =  pd.to_datetime(data['starting_date'], format='%Y-%m-%d')
data['starting_date'] = data['starting_date'].dt.strftime('%Y-%m-%d')

data['ending_date'] =  pd.to_datetime(data['ending_date'], format='%Y-%m-%d')
data['ending_date'] = data['ending_date'].dt.strftime('%Y-%m-%d')

<ipython-input-13-5a68a0a6ac87>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = cd_project_01.append(cd_project_02)
<ipython-input-13-5a68a0a6ac87>:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_03)
<ipython-input-13-5a68a0a6ac87>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_04)
<ipython-input-13-5a68a0a6ac87>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_05)
<ipython-input-13-5a68a0a6ac87>:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_06)
<ipython-input-13-5a68a0a6ac87>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_07)
<ipython-input-13-5a68a0a6ac87>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_08)
<ipython-input-13-5a68a0a6ac87>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_09)
<ipython-input-13-5a68a0a6ac87>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(cd_project_10)

In [14]:
data

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting
0,10.1001/jama.2016.0312,655502,['H2020-MSCA'],MSCA-IF-EF-ST,2015-06-01,2017-12-01,1.0
1,10.1001/jama.2016.1975,669545,['H2020-ERC'],ERC-ADG,2015-11-01,2021-07-31,0.5
1,10.1001/jama.2016.1975,633595,['H2020-SC1'],RIA,2015-04-01,2019-03-31,0.5
2,10.1001/jama.2016.20644,115854,['H2020-SC1'],JTI-IMI2-RIA,2014-12-01,2021-11-30,1.0
3,10.1001/jama.2016.4218,115854,['H2020-SC1'],JTI-IMI2-RIA,2014-12-01,2021-11-30,1.0
...,...,...,...,...,...,...,...
123112,10.7900/jot.2017jan19.2147,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0
123113,10.7900/jot.20181apr19.2188,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0
123114,10.7900/jot.2018jun13.2222,691246,['H2020-MSCA'],MSCA-RISE,2016-01-01,2019-12-31,1.0
123115,10.7900/jot.2018mar08.2219,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0
123116,10.7900/jot.2020feb06.2268,844451,['H2020-MSCA'],MSCA-IF-EF-ST,2019-06-01,2021-05-31,1.0

In [15]:
##############################################################
#progr_proj_id

In [16]:
#select just project_id and progr_proj_id
progr_proj_id = data[['project_id', 'progr_proj_id']]
progr_proj_id = progr_proj_id.sort_values(by=['project_id'], ascending=True)
progr_proj_id = progr_proj_id.drop_duplicates()

#clean progr_proj_id from H2020 and remove non-alphanumeric chars 
progr_proj_id['progr_proj_id'] = progr_proj_id['progr_proj_id'].str.replace('H2020', '')
progr_proj_id['progr_proj_id'] = progr_proj_id['progr_proj_id'].str.replace('\W', ' ')

#strip the string on the left and on the right (remove spaces in the beginning and the end of the string)
progr_proj_id['progr_proj_id'] = progr_proj_id['progr_proj_id'].str.lstrip() 
progr_proj_id['progr_proj_id'] = progr_proj_id['progr_proj_id'].str.rstrip()

<ipython-input-16-53f04e230ae8>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  progr_proj_id['progr_proj_id'] = progr_proj_id['progr_proj_id'].str.replace('\W', ' ')

In [17]:
progr_proj_id

        project_id progr_proj_id
75209       115797           SC1
64605       115842           SC1
94699       115843           SC1
101599      115847           SC1
46189       115848           SC1
...            ...           ...
86429    101017171     LEITs ICT
82889    101017226     LEITs ICT
2468     101023615          MSCA
17567    101025785          MSCA
59568    101026196          MSCA

[13543 rows x 2 columns]

In [18]:
i = progr_proj_id.columns.get_loc('progr_proj_id')
xx = progr_proj_id['progr_proj_id'].str.split(" ", expand=True)
xx2 = pd.concat([progr_proj_id.iloc[:, :i], xx, progr_proj_id.iloc[:, i+1:]], axis=1)
xx2 = xx2.rename(columns={0: 'progr_proj_id_1', 1: 'progr_proj_id_2'})
xx2 = xx2[['project_id', 'progr_proj_id_1', 'progr_proj_id_2']]
xx2

        project_id progr_proj_id_1 progr_proj_id_2
75209       115797             SC1            None
64605       115842             SC1            None
94699       115843             SC1            None
101599      115847             SC1            None
46189       115848             SC1            None
...            ...             ...             ...
86429    101017171           LEITs             ICT
82889    101017226           LEITs             ICT
2468     101023615            MSCA            None
17567    101025785            MSCA            None
59568    101026196            MSCA            None

[13543 rows x 3 columns]

In [19]:
#restructure the dataframe so that each project has a row for each project_id
progr_proj_id_1 = xx2[['project_id', 'progr_proj_id_1']]
progr_proj_id_1 = progr_proj_id_1.rename(columns={'progr_proj_id_1': 'progr_proj_id'})
progr_proj_id_2 = xx2[['project_id', 'progr_proj_id_2']]
progr_proj_id_2 = progr_proj_id_2.rename(columns={'progr_proj_id_2': 'progr_proj_id'})

xx3 = progr_proj_id_1.append(progr_proj_id_2)
xx3 = xx3.drop_duplicates()
xx3 = xx3.sort_values(by=['project_id'], ascending=True)
xx3 = xx3.dropna()

#clean progr_proj_id
xx3 = xx3.loc[(xx3.progr_proj_id != 'Manufacturing') & 
                (xx3.progr_proj_id != 'Space') &
                (xx3.progr_proj_id != 'Materials') &
                (xx3.progr_proj_id != 'Biotech') &
                (xx3.progr_proj_id != 'in') &
                (xx3.progr_proj_id != 'Nano') &
                (xx3.progr_proj_id != 'Innvoation') &
                (xx3.progr_proj_id !=  '0')]

xx3

<ipython-input-19-d5084201f5f7>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  xx3 = progr_proj_id_1.append(progr_proj_id_2)

        project_id progr_proj_id
75209       115797           SC1
64605       115842           SC1
94699       115843           SC1
101599      115847           SC1
46189       115848           SC1
...            ...           ...
82889    101017226           ICT
82889    101017226         LEITs
2468     101023615          MSCA
17567    101025785          MSCA
59568    101026196          MSCA

[14275 rows x 2 columns]

In [20]:
#get dummies for progr_proj_id
dummies_progr_proj_id = pd.get_dummies(xx3, columns=['progr_proj_id'])
dummies_progr_proj_id = dummies_progr_proj_id.groupby(['project_id']).max().reset_index()
dummies_progr_proj_id = dummies_progr_proj_id.sort_values(by=['project_id'], ascending=True)
dummies_progr_proj_id

,project_id,progr_proj_id_ERC,progr_proj_id_FET,progr_proj_id_FTI,progr_proj_id_ICT,progr_proj_id_INFRA,progr_proj_id_LEITs,progr_proj_id_MSCA,progr_proj_id_SC1,progr_proj_id_SC2,progr_proj_id_SC3,progr_proj_id_SC4,progr_proj_id_SC5,progr_proj_id_SC6,progr_proj_id_SC7,progr_proj_id_SEWP,progr_proj_id_SWAFS
0,115797,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,115842,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
2,115843,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
3,115847,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,115848,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13456,101017171,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
13457,101017226,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0
13458,101023615,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
13459,101025785,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
13460,101026196,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [21]:
#save file dummies_progr_proj_id 
data_dir = '/Users/davidebonaglia/Dropbox/Projects UNU/Excellent Science/data_cleaned/'
dummies_progr_proj_id.to_excel(data_dir + 'dummies_progr_proj_id.xlsx', index=False)

In [22]:
############################################################################

In [23]:
#select just project_id and progr_proj_id
action_type_proj_id = data[['project_id', 'action_type_proj_id']]
action_type_proj_id = action_type_proj_id.sort_values(by=['project_id'], ascending=True)
action_type_proj_id = action_type_proj_id.drop_duplicates()
action_type_proj_id

        project_id action_type_proj_id
75209       115797        JTI-IMI2-RIA
64605       115842        JTI-IMI2-RIA
94699       115843        JTI-IMI2-RIA
101599      115847        JTI-IMI2-RIA
46189       115848        JTI-IMI2-RIA
...            ...                 ...
86429    101017171                 RIA
82889    101017226                 RIA
2468     101023615       MSCA-IF-EF-ST
17567    101025785       MSCA-IF-EF-ST
59568    101026196       MSCA-IF-EF-ST

[13543 rows x 2 columns]

In [24]:
i = action_type_proj_id.columns.get_loc('action_type_proj_id')
xx = action_type_proj_id['action_type_proj_id'].str.split("-", expand=True)
xx2 = pd.concat([action_type_proj_id.iloc[:, :i], xx], axis=1)
xx2 = xx2.rename(columns={0: 'action_type_proj_id_1', 1: 'action_type_proj_id_2', 2: 'action_type_proj_id_3', 3: 'action_type_proj_id_4'})
#xx2 = xx2[['project_id', 'progr_proj_id_1', 'progr_proj_id_2']]
xx2

,project_id,action_type_proj_id_1,action_type_proj_id_2,action_type_proj_id_3,action_type_proj_id_4
75209,115797,JTI,IMI2,RIA,None
64605,115842,JTI,IMI2,RIA,None
94699,115843,JTI,IMI2,RIA,None
101599,115847,JTI,IMI2,RIA,None
46189,115848,JTI,IMI2,RIA,None
...,...,...,...,...,...
86429,101017171,RIA,None,None,None
82889,101017226,RIA,None,None,None
2468,101023615,MSCA,IF,EF,ST
17567,101025785,MSCA,IF,EF,ST
59568,101026196,MSCA,IF,EF,ST

In [25]:
#restructure the dataframe so that each project has a row for each project_id
action_type_proj_id_1 = xx2[['project_id', 'action_type_proj_id_1']]
action_type_proj_id_1 = action_type_proj_id_1.rename(columns={'action_type_proj_id_1': 'action_type_proj_id'})

action_type_proj_id_2 = xx2[['project_id', 'action_type_proj_id_2']]
action_type_proj_id_2 = action_type_proj_id_2.rename(columns={'action_type_proj_id_2': 'action_type_proj_id'})

action_type_proj_iD_3 = xx2[['project_id', 'action_type_proj_id_3']]
action_type_proj_iD_3 = action_type_proj_iD_3.rename(columns={'action_type_proj_id_3': 'action_type_proj_id'})

action_type_proj_id_4 = xx2[['project_id', 'action_type_proj_id_4']]
action_type_proj_id_4 = action_type_proj_id_4.rename(columns={'action_type_proj_id_4': 'action_type_proj_id'})

xx3 = action_type_proj_id_1.append(action_type_proj_id_2)
xx3 = xx3.append(action_type_proj_iD_3)
xx3 = xx3.append(action_type_proj_id_4)

xx3 = xx3.drop_duplicates()
xx3 = xx3.sort_values(by=['project_id'], ascending=True)
xx3 = xx3.dropna()

#clean action_type_proj_id
xx3 = xx3.loc[(xx3.action_type_proj_id != '2') & 
                (xx3.action_type_proj_id != '2b')]

xx3

<ipython-input-25-997fecebe3ba>:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  xx3 = action_type_proj_id_1.append(action_type_proj_id_2)
<ipython-input-25-997fecebe3ba>:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  xx3 = xx3.append(action_type_proj_iD_3)
<ipython-input-25-997fecebe3ba>:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  xx3 = xx3.append(action_type_proj_id_4)

       project_id action_type_proj_id
75209      115797                 JTI
75209      115797                IMI2
75209      115797                 RIA
64605      115842                IMI2
64605      115842                 RIA
...           ...                 ...
17567   101025785                  ST
59568   101026196                  IF
59568   101026196                  EF
59568   101026196                MSCA
59568   101026196                  ST

[30878 rows x 2 columns]

In [26]:
#get dummies for action_type_proj_id
dummies_action_type_proj_id = pd.get_dummies(xx3, columns=['action_type_proj_id'])
dummies_action_type_proj_id = dummies_action_type_proj_id.groupby(['project_id']).max().reset_index()
dummies_action_type_proj_id = dummies_action_type_proj_id.sort_values(by=['project_id'], ascending=True)
dummies_action_type_proj_id

,project_id,action_type_proj_id_ADG,action_type_proj_id_BBI,action_type_proj_id_CAR,action_type_proj_id_COFUND,action_type_proj_id_COG,action_type_proj_id_CS2,action_type_proj_id_CSA,action_type_proj_id_Cofund,action_type_proj_id_DEMO,...,action_type_proj_id_RIA,action_type_proj_id_RISE,action_type_proj_id_SE,action_type_proj_id_SESAR,action_type_proj_id_SGA,action_type_proj_id_SME,action_type_proj_id_ST,action_type_proj_id_STG,action_type_proj_id_Shift2Rail,action_type_proj_id_SyG
0,115797,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,115842,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,115843,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,115847,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,115848,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13538,101017171,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13539,101017226,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
13540,101023615,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13541,101025785,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
13542,101026196,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [57]:
#save
data_dir = '/Users/davidebonaglia/Dropbox/Projects UNU/Excellent Science/data_cleaned/'
dummies_action_type_proj_id.to_excel(data_dir + 'dummies_action_type_proj_id.xlsx', index=False)

In [ ]:
################################################

In [59]:
import numpy as np

fractional_counting_data = pd.merge(data, dummies_progr_proj_id, how='left', on='project_id')
fractional_counting_data = pd.merge(fractional_counting_data, dummies_action_type_proj_id, how='left', on='project_id')

fractional_counting_data = fractional_counting_data.fillna(0)

fractional_counting_data['progr_proj_id_ERC'] = fractional_counting_data['progr_proj_id_ERC'].astype(int)
fractional_counting_data['progr_proj_id_FET'] = fractional_counting_data['progr_proj_id_FET'].astype(int)
fractional_counting_data['progr_proj_id_FTI'] = fractional_counting_data['progr_proj_id_FTI'].astype(int)
fractional_counting_data['progr_proj_id_ICT'] = fractional_counting_data['progr_proj_id_ICT'].astype(int)
fractional_counting_data['progr_proj_id_INFRA'] = fractional_counting_data['progr_proj_id_INFRA'].astype(int)
fractional_counting_data['progr_proj_id_LEITs'] = fractional_counting_data['progr_proj_id_LEITs'].astype(int)
fractional_counting_data['progr_proj_id_MSCA'] = fractional_counting_data['progr_proj_id_MSCA'].astype(int)
fractional_counting_data['progr_proj_id_SC1'] = fractional_counting_data['progr_proj_id_SC1'].astype(int)
fractional_counting_data['progr_proj_id_SC2'] = fractional_counting_data['progr_proj_id_SC2'].astype(int)
fractional_counting_data['progr_proj_id_SC3'] = fractional_counting_data['progr_proj_id_SC3'].astype(int)
fractional_counting_data['progr_proj_id_SC4'] = fractional_counting_data['progr_proj_id_SC4'].astype(int)
fractional_counting_data['progr_proj_id_SC5'] = fractional_counting_data['progr_proj_id_SC5'].astype(int)
fractional_counting_data['progr_proj_id_SC6'] = fractional_counting_data['progr_proj_id_SC6'].astype(int)
fractional_counting_data['progr_proj_id_SC7'] = fractional_counting_data['progr_proj_id_SC7'].astype(int)
fractional_counting_data['progr_proj_id_SEWP'] = fractional_counting_data['progr_proj_id_SEWP'].astype(int)
fractional_counting_data['progr_proj_id_SWAFS'] = fractional_counting_data['progr_proj_id_SWAFS'].astype(int)

fractional_counting_data = fractional_counting_data.sort_values(by=['publication', 'project_id', 'starting_date'], ascending=True)

fractional_counting_data

,publication,project_id,progr_proj_id,action_type_proj_id,starting_date,ending_date,fractional_counting,progr_proj_id_ERC,progr_proj_id_FET,progr_proj_id_FTI,...,action_type_proj_id_RIA,action_type_proj_id_RISE,action_type_proj_id_SE,action_type_proj_id_SESAR,action_type_proj_id_SGA,action_type_proj_id_SME,action_type_proj_id_ST,action_type_proj_id_STG,action_type_proj_id_Shift2Rail,action_type_proj_id_SyG
0,10.1001/jama.2016.0312,655502,['H2020-MSCA'],MSCA-IF-EF-ST,2015-06-01,2017-12-01,1.0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,10.1001/jama.2016.1975,633595,['H2020-SC1'],RIA,2015-04-01,2019-03-31,0.5,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,10.1001/jama.2016.1975,669545,['H2020-ERC'],ERC-ADG,2015-11-01,2021-07-31,0.5,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10.1001/jama.2016.20644,115854,['H2020-SC1'],JTI-IMI2-RIA,2014-12-01,2021-11-30,1.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4,10.1001/jama.2016.4218,115854,['H2020-SC1'],JTI-IMI2-RIA,2014-12-01,2021-11-30,1.0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132016,10.7900/jot.2017jan19.2147,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
132017,10.7900/jot.20181apr19.2188,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
132018,10.7900/jot.2018jun13.2222,691246,['H2020-MSCA'],MSCA-RISE,2016-01-01,2019-12-31,1.0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
132019,10.7900/jot.2018mar08.2219,669240,['H2020-ERC'],ERC-ADG,2015-12-01,2021-11-30,1.0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
132020,10.7900/jot.2020feb06.2268,844451,['H2020-MSCA'],MSCA-IF-EF-ST,2019-06-01,2021-05-31,1.0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [60]:
#save
data_dir = '/Users/davidebonaglia/Dropbox/Projects UNU/Excellent Science/data_cleaned/'
fractional_counting_data.to_excel(data_dir + 'fractional_counting_data.xlsx', index=False)